version: '2'

services:
  web:
    build: .
    command: npm start
    links:
      - "db:db"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:9.6

